version: 2.1

parameters:
  kre-image-tag:
    type: string
    default: "latest"
  agent-download-link:
    type: string
    default: "https://github.com/katalon-studio/katalon-agent/releases/download/v1.7.6/katalon-agent-linux-x64-v1.7.6.zip"
  job-info:
    type: string
    default: "vicky test"
  agent-config:
    type: string
    default: ""
  server-url:
    type: string
    default: "https://analytics.katalon.com"
  TESTOPS_API_KEY:
    type: string
    default: "a5c1f077-2ee0-4584-ba26-978ee2e11484"
  TESTOPS_SERVER_URL:
    type: string
    default: "https://analytics.katalon.com"
  TESTOPS_PROJECT_ID:
    type: string
    default: "174435"
  TESTOPS_SESSION_ID:
    type: string
    default: ""

jobs:
  katalon-test:
    docker:
      - image: katalonstudio/katalon:<< pipeline.parameters.kre-image-tag >>
    environment:
      AGENT_DOWNLOAD_LINK: << pipeline.parameters.agent-download-link >>
      JOB_INFO: << pipeline.parameters.job-info >>
      SERVER_URL: << pipeline.parameters.server-url >>
    steps:
      - run:
          name: Run Katalon Test
          command: |
            set -x
            set -o nounset
            
            curl -v -m 10 $SERVER_URL/info

            mkdir /agent

            cd /agent

            wget -O agent "${AGENT_DOWNLOAD_LINK}"
            echo "${JOB_INFO}" >> job.json

            set +x
            echo "<< pipeline.parameters.agent-config >>" >> agentconfig
            set -x
            
            cat agentconfig

            chmod 777 *
            ls -al
            
            xvfb-run -s "-screen 0 $DISPLAY_CONFIGURATION" ./agent start-agent --ci
            ret_code=$?
            
            exit $ret_code

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - katalon-test